services:
  db:
    image: postgres:12.22
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fladan_dev
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/pg-data/:/var/lib/postgresql/data
