import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :fladan, FladanWeb.Endpoint,
  url: [host: "https://fladan.gigalixirapp.com/", scheme: "https", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  check_origin: ["fladan.se", "www.fladan.se", "https://fladan.gigalixirapp.com/"],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
